In [2]:
#import
import numpy as np
import pandas as pd

In [ ]:
np.random.random()


0.8387836249284816

In [36]:
np.random.choice(8, size=2, replace=False)

array([0, 3])

In [4]:
population = np.random.randint(5, 20, size=(2, 50, 48))

population

array([[[17, 19, 16, ..., 11,  7,  6],
        [ 7,  9, 13, ..., 18,  9,  6],
        [15, 19, 12, ..., 12, 10, 13],
        ...,
        [ 9, 11, 18, ..., 12, 12, 14],
        [19,  8,  9, ..., 18, 13, 15],
        [11, 10,  6, ...,  5, 15, 11]],

       [[15, 17, 11, ..., 13, 18, 17],
        [16, 15,  9, ..., 17, 10, 19],
        [11,  7, 16, ...,  7, 14, 18],
        ...,
        [17, 10, 13, ...,  9, 13, 15],
        [ 7, 13, 16, ..., 13, 13, 12],
        [17,  8, 11, ..., 13, 19, 11]]])

In [5]:
T = np.random.random((2, 3)) * 50 + 50

T

array([[75.1930573 , 62.10683961, 92.5878609 ],
       [69.78319186, 92.32945479, 66.44463438]])

In [6]:
np.array([-2,-2]).shape

(2,)

In [7]:
n_machine, n_job = np.vstack([[1, 2, 3], [1, 2, 3]]).shape

print(n_machine, n_job)

2 3


In [8]:
from core import previous_recipe

ImportError: cannot import name 'previous_recipe' from 'core' (c:\Users\NHPHUC\Desktop\learn-data-science\schantt-model\core.py)

In [ ]:
np.array([2, 3, 5, 6, 7, 8, 9, 11, 13, 15])

array([ 2,  3,  5,  6,  7,  8,  9, 11, 13, 15])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
v = np.linspace(10, 49, 5)

v

array([10.  , 19.75, 29.5 , 39.25, 49.  ])

In [ ]:
constr_ieq = [
    lambda x: np.sum((x - 1) ** 2)
]

constr_ieq

[<function __main__.<lambda>(x)>]

In [ ]:
np.sum((5 - 1) ** 2)

np.int64(16)

In [ ]:
np.random.rand(3, 10)

array([[0.79763244, 0.91974471, 0.93792657, 0.79194737, 0.25211323,
        0.47761908, 0.27194703, 0.09614532, 0.39073015, 0.0384781 ],
       [0.27731339, 0.01329934, 0.57936962, 0.82561941, 0.54289269,
        0.30953572, 0.04503203, 0.92002021, 0.91243182, 0.00625146],
       [0.49915341, 0.81511024, 0.73845997, 0.12912813, 0.32189419,
        0.28963681, 0.38787947, 0.16833655, 0.11282589, 0.72374424]])

In [ ]:
from pymoo.problems import get_problem
from pymoo.visualization.fitness_landscape import FitnessLandscape

In [ ]:
np.full((3, 2), 0)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
from pymoo.problems import get_problem